#!/bin/bash

FILENAME=$1
FILE_NEXT=${FILENAME%.*}
DIRNAME=$(dirname $FILENAME)
tmpfile=$(mktemp llvm_compiler.XXXXXX)

./LLVMCompiler ${FILENAME}
llvm-as -o $tmpfile ${FILE_NEXT}.ll
llvm-link -o ${FILE_NEXT}.bc $tmpfile lib/runtime.bc
rm $tmpfile
